# {"Nom": "","Symbole": "","Phase": "","Categorie": "","Numéro": ,"Xpos": ,"Ypos": },
Period = [
 {"Nom": "Hydrogène","Symbole": "H","Phase": "Gaz","Categorie": "Non-métal","Numéro": 1,"Xpos": 1,"Ypos": 1},
 {"Nom": "Helium","Symbole": "He","Phase": "Gaz","Categorie": "Gaz noble","Numéro": 2,"Xpos": 18,"Ypos": 1},
 {"Nom": "Lithium","Symbole": "Li","Phase": "Solide","Categorie": "Alcalin","Numéro": 3,"Xpos": 1,"Ypos": 2},
 {"Nom": "Beryllium","Symbole": "Be","Phase": "Solide","Categorie": "Alc-terreu","Numéro": 4,"Xpos": 2,"Ypos": 2},
 {"Nom": "Bore","Symbole": "B","Phase": "Solide","Categorie": "Métaloïde","Numéro": 5,"Xpos": 13,"Ypos": 2},
 {"Nom": "Carbone","Symbole": "C","Phase": "Solide","Categorie": "Non-métal","Numéro": 6,"Xpos": 14,"Ypos": 2},
 {"Nom": "Azote","Symbole": "N","Phase": "Gaz","Categorie": "Non-métal","Numéro": 7,"Xpos": 15,"Ypos": 2},
 {"Nom": "Oxygène","Symbole": "O","Phase": "Gaz","Categorie": "Non-métal","Numéro": 8,"Xpos": 16,"Ypos": 2},
 {"Nom": "Fluore","Symbole": "F","Phase": "Gaz","Categorie": "Halogène","Numéro": 9,"Xpos": 17,"Ypos": 2},
 {"Nom": "Neon","Symbole": "Ne","Phase": "Gaz","Categorie": "Gaz noble","Numéro": 10,"Xpos": 18,"Ypos": 2},
 {"Nom": "Sodium","Symbole": "Na","Phase": "Solide","Categorie": "Alcalin","Numéro": 11,"Xpos": 3,"Ypos": 1},
 {"Nom": "Magnésium","Symbole": "Mg","Phase": "Solide","Categorie": "Alc-terreu","Numéro": 12,"Xpos": 2,"Ypos": 3},
 {"Nom": "Aluminium","Symbole": "Al","Phase": "Solide","Categorie": "Métal pauvre","Numéro": 13,"Xpos": 13,"Ypos": 3},
 {"Nom": "Silicon","Symbole": "Si","Phase": "Solide","Categorie": "Métaloïde","Numéro": 14,"Xpos": 14,"Ypos": 3},
 {"Nom": "Phosphore","Symbole": "P","Phase": "Solide","Categorie": "Non-métal","Numéro": 15,"Xpos": 15,"Ypos": 3},
 {"Nom": "Soufre","Symbole": "S","Phase": "Solide","Categorie": "Non-métal","Numéro": 16,"Xpos": 16,"Ypos": 3},
 {"Nom": "Chlore","Symbole": "Cl","Phase": "Gaz","Categorie": "Halogène","Numéro": 17,"Xpos": 17,"Ypos": 3},
 {"Nom": "Argon","Symbole": "Ar","Phase": "Gaz","Categorie": "Gaz noble","Numéro": 18,"Xpos": 18,"Ypos": 3},
 {"Nom": "Potassium","Symbole": "K","Phase": "Solide","Categorie": "","Numéro": 19,"Xpos": 1,"Ypos": 4},
 {"Nom": "","Symbole": "","Phase": "","Categorie": "","Numéro": 20,"Xpos": 2,"Ypos": 4},
 {"Nom": "","Symbole": "","Phase": "","Categorie": "","Numéro": 21,"Xpos": 3,"Ypos": 4},
 {"Nom": "","Symbole": "","Phase": "","Categorie": "","Numéro": 22,"Xpos": 4,"Ypos": 4},
 {"Nom": "","Symbole": "","Phase": "","Categorie": "","Numéro": 23,"Xpos": 5,"Ypos": 4},
 {"Nom": "","Symbole": "","Phase": "","Categorie": "","Numéro": 24,"Xpos": 6,"Ypos": 4},
 {"Nom": "","Symbole": "","Phase": "","Categorie": "","Numéro": 25,"Xpos": 7,"Ypos": 4},
 {"Nom": "","Symbole": "","Phase": "","Categorie": "","Numéro": 26,"Xpos": 8,"Ypos": 4},
 {"Nom": "","Symbole": "","Phase": "","Categorie": "","Numéro": 27,"Xpos": 9,"Ypos": 4},
 {"Nom": "","Symbole": "","Phase": "","Categorie": "","Numéro": 28,"Xpos": 10,"Ypos": 4},
 {"Nom": "","Symbole": "","Phase": "","Categorie": "","Numéro": 29,"Xpos": 11,"Ypos": 4},
 {"Nom": "","Symbole": "","Phase": "","Categorie": "","Numéro": 30,"Xpos": 12,"Ypos": 4},
 {"Nom": "","Symbole": "","Phase": "","Categorie": "","Numéro": 31,"Xpos": 13,"Ypos": 4},
 {"Nom": "","Symbole": "","Phase": "","Categorie": "","Numéro": 32,"Xpos": 14,"Ypos": 4},
 {"Nom": "","Symbole": "","Phase": "","Categorie": "","Numéro": 33,"Xpos": 15,"Ypos": 4},
 {"Nom": "","Symbole": "","Phase": "","Categorie": "","Numéro": 34,"Xpos": 16,"Ypos": 4},
 {"Nom": "","Symbole": "","Phase": "","Categorie": "","Numéro": 35,"Xpos": 17,"Ypos": 4},
 {"Nom": "","Symbole": "","Phase": "","Categorie": "","Numéro": 36,"Xpos": 18,"Ypos": 4},
 {"Nom": "","Symbole": "","Phase": "","Categorie": "","Numéro": 37,"Xpos": 1,"Ypos": 5},
 {"Nom": "","Symbole": "","Phase": "","Categorie": "","Numéro": 38,"Xpos": 2,"Ypos": 5},
 {"Nom": "","Symbole": "","Phase": "","Categorie": "","Numéro": 39,"Xpos": 3,"Ypos": 5},
 {"Nom": "","Symbole": "","Phase": "","Categorie": "","Numéro": 40,"Xpos": 4,"Ypos": 5},
 {"Nom": "","Symbole": "","Phase": "","Categorie": "","Numéro": 41,"Xpos": 5,"Ypos": 5},
 {"Nom": "","Symbole": "","Phase": "","Categorie": "","Numéro": 42,"Xpos": 6,"Ypos": 5},
 {"Nom": "","Symbole": "","Phase": "","Categorie": "","Numéro": 43,"Xpos": 7,"Ypos": 5},
 {"Nom": "","Symbole": "","Phase": "","Categorie": "","Numéro": 44,"Xpos": 8,"Ypos": 5},
 {"Nom": "","Symbole": "","Phase": "","Categorie": "","Numéro": 45,"Xpos": 9,"Ypos": 5},
 {"Nom": "","Symbole": "","Phase": "","Categorie": "","Numéro": 46,"Xpos": 10,"Ypos": 5},
 {"Nom": "","Symbole": "","Phase": "","Categorie": "","Numéro": 47,"Xpos": 11,"Ypos": 5},
 {"Nom": "","Symbole": "","Phase": "","Categorie": "","Numéro": 48,"Xpos": 12,"Ypos": 5},
 {"Nom": "","Symbole": "","Phase": "","Categorie": "","Numéro": 49,"Xpos": 13,"Ypos": 5},
 {"Nom": "","Symbole": "","Phase": "","Categorie": "","Numéro": 50,"Xpos": 14,"Ypos": 5},
 {"Nom": "","Symbole": "","Phase": "","Categorie": "","Numéro": 51,"Xpos": 15,"Ypos": 5},
 {"Nom": "","Symbole": "","Phase": "","Categorie": "","Numéro": 52,"Xpos": 16,"Ypos": 5},
 {"Nom": "","Symbole": "","Phase": "","Categorie": "","Numéro": 53,"Xpos": 17,"Ypos": 5},
 {"Nom": "","Symbole": "","Phase": "","Categorie": "","Numéro": 54,"Xpos": 18,"Ypos": 5},
]