Period = [
 {"Nom": "Hydrogène","Symbole": "H","Phase": "Gaz","Categorie": "Non-métal","Numéro": 1,"Xpos": 1,"Ypos": 1},
 {"Nom": "Helium","Symbole": "He","Phase": "Gaz","Categorie": "Gaz noble","Numéro": 2,"Xpos": 18,"Ypos": 1},
 {"Nom": "Lithium","Symbole": "Li","Phase": "Solide","Categorie": "Alcalin","Numéro": 3,"Xpos": 1,"Ypos": 2},
 {"Nom": "Beryllium","Symbole": "Be","Phase": "Solide","Categorie": "Alc-terreu","Numéro": 4,"Xpos": 2,"Ypos": 2},
 {"Nom": "Bore","Symbole": "B","Phase": "Solide","Categorie": "Métaloïde","Numéro": 5,"Xpos": 13,"Ypos": 2},
 {"Nom": "Carbone","Symbole": "C","Phase": "Solide","Categorie": "Non-métal","Numéro": 6,"Xpos": 14,"Ypos": 2},
 {"Nom": "Azote","Symbole": "N","Phase": "Gaz","Categorie": "Non-métal","Numéro": 7,"Xpos": 15,"Ypos": 2},
 {"Nom": "Oxygène","Symbole": "O","Phase": "Gaz","Categorie": "Non-métal","Numéro": 8,"Xpos": 16,"Ypos": 2},
 {"Nom": "Fluore","Symbole": "F","Phase": "Gaz","Categorie": "Halogène","Numéro": 9,"Xpos": 17,"Ypos": 2},
 {"Nom": "Neon","Symbole": "Ne","Phase": "Gaz","Categorie": "Gaz noble","Numéro": 10,"Xpos": 18,"Ypos": 2},
 {"Nom": "Sodium","Symbole": "Na","Phase": "Solide","Categorie": "Alcalin","Numéro": 11,"Xpos": 3,"Ypos": 1},
 {"Nom": "Magnésium","Symbole": "Mg","Phase": "Solide","Categorie": "Alc-terreu","Numéro": 12,"Xpos": 2,"Ypos": 3},
 {"Nom": "Aluminium","Symbole": "Al","Phase": "Solide","Categorie": "Métal pauvre","Numéro": 13,"Xpos": 13,"Ypos": 3},
 {"Nom": "Silicon","Symbole": "Si","Phase": "Solide","Categorie": "Métaloïde","Numéro": 14,"Xpos": 14,"Ypos": 3},
 {"Nom": "Phosphore","Symbole": "P","Phase": "Solide","Categorie": "Non-métal","Numéro": 15,"Xpos": 15,"Ypos": 3},
 {"Nom": "Soufre","Symbole": "S","Phase": "Solide","Categorie": "Non-métal","Numéro": 16,"Xpos": 16,"Ypos": 3},
 {"Nom": "Chlore","Symbole": "Cl","Phase": "Gaz","Categorie": "Halogène","Numéro": 17,"Xpos": 17,"Ypos": 3},
 {"Nom": "Argon","Symbole": "Ar","Phase": "Gaz","Categorie": "Gaz noble","Numéro": 18,"Xpos": 18,"Ypos": 3},
 {"Nom": "Potassium","Symbole": "K","Phase": "Solide","Categorie": "Alcalin","Numéro": 19,"Xpos": 1,"Ypos": 4},
 {"Nom": "Calcium","Symbole": "Ca","Phase": "Solide","Categorie": "Alc-terreu","Numéro": 20,"Xpos": 2,"Ypos": 4},
 {"Nom": "Scandium","Symbole": "Sc","Phase": "Solide","Categorie": "Mt de trans","Numéro": 21,"Xpos": 3,"Ypos": 4},
 {"Nom": "Titane","Symbole": "Ti","Phase": "Solide","Categorie": "Mt de trans","Numéro": 22,"Xpos": 4,"Ypos": 4},
 {"Nom": "Vanadium","Symbole": "V","Phase": "Solide","Categorie": "Mt de trans","Numéro": 23,"Xpos": 5,"Ypos": 4},
 {"Nom": "Chrome","Symbole": "Cr","Phase": "Solide","Categorie": "Mt de trans","Numéro": 24,"Xpos": 6,"Ypos": 4},
 {"Nom": "Manganèse","Symbole": "Mn","Phase": "Solide","Categorie": "Mt de trans","Numéro": 25,"Xpos": 7,"Ypos": 4},
 {"Nom": "Fer","Symbole": "Fe","Phase": "Solide","Categorie": "Mt de trans","Numéro": 26,"Xpos": 8,"Ypos": 4},
 {"Nom": "Cobalt","Symbole": "Co","Phase": "Solide","Categorie": "Mt de trans","Numéro": 27,"Xpos": 9,"Ypos": 4},
 {"Nom": "Nickel","Symbole": "Ni","Phase": "Solide","Categorie": "Mt de trans","Numéro": 28,"Xpos": 10,"Ypos": 4},
 {"Nom": "Cuivre","Symbole": "Cu","Phase": "Solide","Categorie": "Mt de trans","Numéro": 29,"Xpos": 11,"Ypos": 4},
 {"Nom": "Zinc","Symbole": "Zn","Phase": "Solide","Categorie": "Mt de trans","Numéro": 30,"Xpos": 12,"Ypos": 4},
 {"Nom": "Gallium","Symbole": "Ga","Phase": "Solide","Categorie": "Métal pauvre","Numéro": 31,"Xpos": 13,"Ypos": 4},
 {"Nom": "Germanium","Symbole": "Ge","Phase": "Solide","Categorie": "Métaloïde", "Numéro": 32,"Xpos": 14,"Ypos": 4},
 {"Nom": "Arsenic","Symbole": "As","Phase": "Solide","Categorie": "Métaloïde","Numéro": 33,"Xpos": 15,"Ypos": 4},
 {"Nom": "Sélénium","Symbole": "Se","Phase": "Solide","Categorie": "Non-métal","Numéro": 34,"Xpos": 16,"Ypos": 4},
 {"Nom": "Brome","Symbole": "Br","Phase": "Liquide","Categorie": "Halogène","Numéro": 35,"Xpos": 17,"Ypos": 4},
 {"Nom": "Krypton","Symbole": "Kr","Phase": "Gaz","Categorie": "Gaz noble","Numéro": 36,"Xpos": 18,"Ypos": 4},
 {"Nom": "Rubidium","Symbole": "Rb","Phase": "Solide","Categorie": "Alcalin","Numéro": 37,"Xpos": 1,"Ypos": 5},
 {"Nom": "Strontium","Symbole": "Sr","Phase": "Solide","Categorie": "Alc-terreu","Numéro": 38,"Xpos": 2,"Ypos": 5},
 {"Nom": "Yttrium","Symbole": "Y","Phase": "Solide","Categorie": "Mt de trans","Numéro": 39,"Xpos": 3,"Ypos": 5},
 {"Nom": "Zirconium","Symbole": "Zr","Phase": "Solide","Categorie": "Mt de trans","Numéro": 40,"Xpos": 4,"Ypos": 5},
 {"Nom": "Niobium","Symbole": "Nb","Phase": "Solide","Categorie": "Mt de trans","Numéro": 41,"Xpos": 5,"Ypos": 5},
 {"Nom": "Molybdène","Symbole": "Mo","Phase": "Solide","Categorie": "Mt de trans","Numéro": 42,"Xpos": 6,"Ypos": 5},
 {"Nom": "Technétium","Symbole": "Tc","Phase": "Solide","Categorie": "Mt de trans","Numéro": 43,"Xpos": 7,"Ypos": 5},
 {"Nom": "Ruthénium","Symbole": "Ru","Phase": "Solide","Categorie": "Mt de trans","Numéro": 44,"Xpos": 8,"Ypos": 5},
 {"Nom": "Rhodium","Symbole": "Rh","Phase": "Solide","Categorie": "Mt de trans","Numéro": 45,"Xpos": 9,"Ypos": 5},
 {"Nom": "Palladium","Symbole": "Pd","Phase": "Solide","Categorie": "Mt de trans","Numéro": 46,"Xpos": 10,"Ypos": 5},
 {"Nom": "Argent","Symbole": "Ag","Phase": "Solide","Categorie": "Mt de trans","Numéro": 47,"Xpos": 11,"Ypos": 5},
 {"Nom": "Cadmium","Symbole": "Cd","Phase": "Solide","Categorie": "Mt de trans","Numéro": 48,"Xpos": 12,"Ypos": 5},
 {"Nom": "Indium","Symbole": "In","Phase": "Solide","Categorie": "Métal pauvre","Numéro": 49,"Xpos": 13,"Ypos": 5},
 {"Nom": "Etain","Symbole": "Sn","Phase": "Solide","Categorie": "Métal pauvre","Numéro": 50,"Xpos": 14,"Ypos": 5},
 {"Nom": "Antimoine","Symbole": "Sb","Phase": "Solide","Categorie": "Métaloïde","Numéro": 51,"Xpos": 15,"Ypos": 5},
 {"Nom": "Tellure","Symbole": "Te","Phase": "Solide","Categorie": "Métaloïde","Numéro": 52,"Xpos": 16,"Ypos": 5},
 {"Nom": "Iode","Symbole": "I","Phase": "Solide","Categorie": "Halogène","Numéro": 53,"Xpos": 17,"Ypos": 5},
 {"Nom": "Xénon","Symbole": "Xe","Phase": "Gaz","Categorie": "Gaz noble","Numéro": 54,"Xpos": 18,"Ypos": 5}
]